In [1]:
# numpy作为python数据处理最常用的模块被广泛使用。
import numpy as np

In [7]:
# numpy.log(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
# x: 输入
# return: x的自然对数
# e.g.
np.log([1, np.e, np.e**2, 0])
# array([  0.,   1.,   2., -Inf])

<ipython-input-7-2ed7b7ed1bcf>:5: RuntimeWarning: divide by zero encountered in log
  np.log([1, np.e, np.e**2, 0])


array([  0.,   1.,   2., -inf])

In [8]:
# numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
# a: 输入数组
# axis: 均值计算的轴，默认会将数组打平（flatten）后计算均值
# return: 指定轴的均值或均值向量
# e.g.
a = np.array([[1, 2], [3, 4]])
np.mean(a) # 计算指定axis下的算术平均值。

2.5

In [9]:
# numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)[source]
# 参数同np.mean()函数
# e.g.
a = np.array([[1, 2], [3, 4]])
np.std(a) # 计算指定axis下的标准差。

1.118033988749895

In [10]:
# numpy.empty(shape, dtype=float, order='C', *, like=None)
# shape: 矩阵形状
# dtype: 数据类型，默认为numpy.float64.
# return: 指定维度的未被初始化（数值任意）的矩阵
# e.g.
np.empty([2, 2], dtype=int) # 返回给定形状和类型的矩阵。

array([[1, 2],
       [3, 4]])

In [12]:
# numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
# object: 数组，或者任何可以显示数组接口的对象。（注：一般是python列表）
# dtype: 数据类型，如果不给出，则该类型将确定为按顺序保留对象所需的最小类型
# return: numpy格式的数组
# e.g.
np.array([[1, 2], [3, 4]]) # 创建一个数组。

array([[1, 2],
       [3, 4]])

In [17]:
# np.zeros() ：返回指定形状下的全零数组。
# np.ones() ：返回指定形状下的全1数组。
# np.eye() ：返回指定形状下的单位阵。
print("np.zeros: {}".format(np.zeros(5)))
print("np.ones: {}".format(np.ones(5)))
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
# N: 输出数组行数
# M: 可选，输出数组列数，默认等于行数
# dtype: 数据类型，默认为numpy.float64.
# e.g.
np.eye(2, dtype=int)

np.zeros: [0. 0. 0. 0. 0.]
np.ones: [1. 1. 1. 1. 1.]


array([[1, 0],
       [0, 1]])

In [18]:
# 使用 Python 序列（例如列表和元组）定义 NumPy 数组。列表和元组分别使用[…]和定义(…)
a1D = np.array([1, 2, 3, 4])
